import { NextResponse } from "next/server";

const references = [
  {
    title: "Reference 1",
    url: "https://url-to-reference-1.com",
    excerpt:
      "You can fetch these references from an API endpoint based on the user query. This can be useful for providing additional information to users, or for displaying related content.",
  },
  {
    title: "Reference 2",
    url: "https://url-to-reference-2.com",
    excerpt:
      "You can send these references to your LLM model to help it generate more relevant responses. This can help improve the quality of the responses generated by the model.",
  },
];

export async function POST(req: Request) {
  const { messages } = await req.json();
  const response = {
    messages,
    references,
  };
  return new NextResponse(JSON.stringify(response), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
    },
  });
}
